/*************************************************************
//-- This function was generated by DeepSeek, 2025-09-25

//-- Examples of use
$(document).ready(function() {
    // Мигание по ID
    blinkElement('#myDiv', {
        color: '#ff0000',
        duration: 2000,
        blinkSpeed: 300
    });
    
    //-- Blinking by class
    blinkElement('.alert', {
        color: '#00ff00',
        duration: 3000
    });
    
    //-- Blinking multiple elements with a delay
    $('.item').each(function(index) {
        setTimeout(() => {
            blinkElement($(this), {
                color: '#0000ff',
                duration: 1500
            });
        }, index * 200);
    });
    
    //-- Using the simplified version
    $('#myDiv').blink({
        color: '#ff9900',
        times: 3,
        speed: 300
    });
});
*************************************************************/
function blinkElement(selector, options = {}) {
    const config = {
        duration: 2000,
        color: '#ffff00',
        blinkSpeed: 200,
        originalColor: '',
        ...options
    };
    
    const $element = $(selector);
    
    if ($element.length === 0) {
        console.error('Элемент не найден:', selector);
        return;
    }
    
    // Сохраняем исходные стили
    const originalStyle = {
        backgroundColor: $element.css('backgroundColor'),
        transition: $element.css('transition')
    };
    
    // Устанавливаем плавный переход
    $element.css('transition', 'background-color 0.2s ease');
    
    let isBlinking = true;
    const blinkInterval = setInterval(() => {
        $element.css('backgroundColor', isBlinking 
            ? config.color 
            : (config.originalColor || originalStyle.backgroundColor));
        isBlinking = !isBlinking;
    }, config.blinkSpeed);
    
    // Останавливаем мигание
    setTimeout(() => {
        clearInterval(blinkInterval);
        $element.css('backgroundColor', config.originalColor || originalStyle.backgroundColor);
        
        // Через немного времени убираем transition
        setTimeout(() => {
            $element.css('transition', originalStyle.transition);
        }, 200);
        
    }, config.duration);
}

