- platform: template
  sensors:
    matter_devices_count:
      value_template: |-
        {%- set ns1 = namespace(num_matter_devices = 0) -%}
        {%- set state = states('sensor.matter_devices') -%}
        {%- if(state != 'unknown' and state != 'unavailable' and state != 'none') -%}
          {%- set devices = state_attr('sensor.matter_devices', 'devices') | default([]) -%}
          {#%- if prop_value is not none -%#}
          
          {{ devices | length }}
        {%- else -%}
          0
        {%- endif -%}
      friendly_name: "Matter Devices Count"
    matter_devices:
      value_template: |-
        {{ "OK" }}
      friendly_name: "Matter Devices"
      attribute_templates:
        friendly_name: "Matter Devices List"
        devices: |-
          {%- set ns1 = namespace(all_matter_devices = []) -%}
        
          {# Шаг 1: Поиск устройств Matter через сущности #}
          {%- for entity_id in states | map(attribute='entity_id') | list -%}
            {%- set device_id = device_id(entity_id) -%}
            {%- if device_id is not none -%}
              {%- set identifiers = device_attr(device_id, 'identifiers') -%}
              {%- if identifiers is not none -%}
                {%- for identifier_pair in identifiers -%}
                  {%- if identifier_pair is sequence and identifier_pair | first == 'matter' -%}
                    {%- set ns1.all_matter_devices = ns1.all_matter_devices + [device_id] -%}
                  {%- endif -%}
                {%- endfor -%}
              {%- endif -%}
            {%- endif -%}
          {%- endfor -%}
          
          {# Шаг 2: Добавление "сиротских" устройств Matter из сенсора #}
          
          {%- set state = states('sensor.orphaned_matter_devices') -%}
          {%- if(state != 'unknown' and state != 'unavailable' and state != 'none') -%}
            {%- set orphaned_devices_from_sensor = state_attr('sensor.orphaned_matter_devices', 'devices') | default([]) -%}
            {%- for device in orphaned_devices_from_sensor -%}
              {%- set ns1.all_matter_devices = ns1.all_matter_devices + [device.id] -%}
            {%- endfor -%}
          {%- endif -%}
          
          {%- set unique_matter_devices = ns1.all_matter_devices | unique | list -%}

          {%- set ns0 = namespace(global_list_of_items=[]) -%}
          
          {%- set ns = namespace(manufacturer = '') -%}
          {%- set ns = namespace(model = '') -%}
          {%- set ns = namespace(hw_version = '') -%}
          {%- set ns = namespace(sw_version = '') -%}
          {%- set ns = namespace(suggested_area = '') -%}
          {%- set ns = namespace(via_device_id = '') -%}
          {%- set ns = namespace(entry_type = '') -%}
          {%- set ns = namespace(configuration_url = '') -%}
          {%- set ns = namespace(identifiers = '') -%}

          {%- if unique_matter_devices | length > 0 -%}
            {%- for device_id in unique_matter_devices -%}

              {%- for prop in ['name', 'manufacturer','model','hw_version','sw_version','suggested_area','via_device_id','entry_type','configuration_url','identifiers'] -%}
                {%- set prop_value = device_attr(device_id, prop) -%}
                {%- if prop_value is not none -%}
                  
                  {%- if prop == 'name' -%}
                    {%- set ns.name = prop_value -%}
                  {%- elif prop == 'manufacturer' -%}
                    {%- set ns.manufacturer = prop_value -%}
                  {%- elif prop == 'model' -%}
                    {%- set ns.model = prop_value -%}
                  {%- elif prop == 'hw_version' -%}
                    {%- set ns.hw_version = prop_value -%}
                  {%- elif prop == 'sw_version' -%}
                    {%- set ns.sw_version = prop_value -%}
                  {%- elif prop == 'suggested_area' -%}
                    {%- set ns.suggested_area = prop_value -%}
                  {%- elif prop == 'via_device_id' -%}
                    {%- set ns.via_device_id = prop_value -%}
                  {%- elif prop == 'entry_type' -%}
                    {%- set ns.entry_type = prop_value -%}
                  {%- elif prop == 'configuration_url' -%}
                    {%- set ns.configuration_url = prop_value -%}
                  {%- elif prop == 'identifiers' -%}
                    {%- set ns.identifiers = prop_value -%}
                  {%- endif -%}

                {%- endif -%}
              {%- endfor -%}
              
              {%- set local_item_block = {
                'name': device_name(device_id),
                'id': device_id,
                'manufacturer': ns.manufacturer,
                'model': ns.model,
                'hw_version': ns.hw_version,
                'sw_version': ns.sw_version,
                'suggested_area': ns.suggested_area,
                'via_device_id': ns.via_device_id,
                'entry_type': ns.entry_type,
                'configuration_url': ns.configuration_url,
                'identifiers': ns.identifiers,
              } -%}

              {%- set ns0.global_list_of_items = ns0.global_list_of_items + [local_item_block] -%}
            {%- endfor -%}
          {%- else -%}
            Устройства Matter/Thread не найдены.
          {%- endif -%}
          
          {{ns0.global_list_of_items}}

          {#
          
          {{"\n\n"}}

          {%- set list = [1,2,3] -%}
          {%- set ns = namespace(items=[]) -%}
            {%- for item in list -%}
              {%- set item_info = {
                'name': 'name',
                'entity_id': list,
                'state': 'state'
              } -%}
              {%- set ns.items = ns.items + [item_info] -%}
            {%- endfor -%}
            {{ ns.items }}

            #}
